# Generated by Django 4.0.3 on 2024-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='href',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
