# Generated by Django 4.0.3 on 2024-03-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
